/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <game.h>
#include <android/log.h>
/* Header for class com_danegor_asteroidsgame_GameSurfaceView */

#define APPNAME "com.danegor.asteroidsgame"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,APPNAME,__VA_ARGS__)

#ifndef _Included_com_danegor_asteroidsgame_GameSurfaceView
#define _Included_com_danegor_asteroidsgame_GameSurfaceView
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_danegor_asteroidsgame_GameSurfaceView_nativeTouch
  (JNIEnv *env, jclass, jfloatArray xs, jfloatArray ys, jint size, jint ev) {
	jfloat* cxs = env->GetFloatArrayElements(xs, 0);
	jfloat* cys = env->GetFloatArrayElements(ys, 0);
	on_touch(cxs, cys, size, ev);
	env->ReleaseFloatArrayElements(xs, cxs, 0);
	env->ReleaseFloatArrayElements(ys, cys, 0);
}

JNIEXPORT void JNICALL Java_com_danegor_asteroidsgame_GameRenderer_nativeInit
  (JNIEnv *, jclass, jint w, jint h) {
	on_init(w, h);
}

JNIEXPORT void JNICALL Java_com_danegor_asteroidsgame_GameRenderer_nativeRender
  (JNIEnv *, jclass) {
	on_render();
}

#ifdef __cplusplus
}
#endif
#endif
